/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ComponentStatus */
    ComponentStatus: {
      /**
       * Status
       * @enum {string}
       */
      status: "up" | "down" | "disabled";
      /** Detail */
      detail?: string | null;
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded";
      /** App */
      app: string;
      /** Version */
      version: string;
      database: components["schemas"]["ComponentStatus"];
      redis: components["schemas"]["ComponentStatus"];
      /** Providers */
      providers: components["schemas"]["ProviderStatus"][];
    };
    /** ProviderStatus */
    ProviderStatus: {
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: "up" | "down" | "disabled" | "degraded";
      /** Detail */
      detail?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
}
