"""core schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-31 12:26:16.096652

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.db.types  # custom column types are rendered fully qualified

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "low", "medium", "high", "manual", name="bet_tier", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "placed",
                "settled",
                "void",
                name="bet_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stake", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("combined_price_decimal", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("combined_probability", sa.Float(), nullable=False),
        sa.Column("naive_probability", sa.Float(), nullable=True),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("kelly_fraction", sa.Float(), nullable=True),
        sa.Column("bankroll_at_placement", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("placed_at", app.db.types.TZDateTime(timezone=True), nullable=True),
        sa.Column("settled_at", app.db.types.TZDateTime(timezone=True), nullable=True),
        sa.Column("payout", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'placed', 'settled', 'void')", name=op.f("ck_bets_status_valid")
        ),
        sa.CheckConstraint(
            "tier IN ('low', 'medium', 'high', 'manual')", name=op.f("ck_bets_tier_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bets")),
    )
    with op.batch_alter_table("bets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bets_status"), ["status"], unique=False)

    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_name", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running", "success", "failure", name="job_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("started_at", app.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", app.db.types.TZDateTime(timezone=True), nullable=True),
        sa.Column("rows_fetched", sa.Integer(), nullable=False),
        sa.Column("rows_upserted", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failure')", name=op.f("ck_ingest_jobs_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_jobs")),
    )
    with op.batch_alter_table("ingest_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingest_jobs_name_started", ["job_name", "started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ingest_jobs_status"), ["status"], unique=False)

    op.create_table(
        "raw_ingest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("fetched_at", app.db.types.TZDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_ingest")),
    )
    with op.batch_alter_table("raw_ingest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_ingest_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_raw_ingest_fetched_at"), ["fetched_at"], unique=False)
        batch_op.create_index(
            "ix_raw_ingest_provider_endpoint_time",
            ["provider", "endpoint", "fetched_at"],
            unique=False,
        )

    op.create_table(
        "sports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("team", "combat", name="sport_kind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('team', 'combat')", name=op.f("ck_sports_kind_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sports")),
        sa.UniqueConstraint("slug", name=op.f("uq_sports_slug")),
    )
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("altitude_m", sa.Integer(), nullable=True),
        sa.Column("is_indoor", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_venues")),
    )
    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_venues_name"), ["name"], unique=False)

    op.create_table(
        "entity_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "team",
                "player",
                "league",
                "fixture",
                name="entity_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("alias_name", sa.String(length=200), nullable=True),
        sa.Column("normalized_alias", sa.String(length=200), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "provider_id",
                "exact",
                "fuzzy",
                "manual",
                name="alias_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('team', 'player', 'league', 'fixture')",
            name=op.f("ck_entity_aliases_entity_type_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('provider_id', 'exact', 'fuzzy', 'manual')",
            name=op.f("ck_entity_aliases_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_entity_aliases_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_aliases")),
        sa.UniqueConstraint(
            "entity_type", "provider", "external_id", name="uq_entity_aliases_provider_external_id"
        ),
        sa.UniqueConstraint(
            "entity_type",
            "provider",
            "sport_id",
            "normalized_alias",
            name="uq_entity_aliases_provider_sport_alias",
        ),
    )
    with op.batch_alter_table("entity_aliases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_aliases_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(
            "ix_entity_aliases_lookup",
            ["entity_type", "provider", "normalized_alias"],
            unique=False,
        )

    op.create_table(
        "leagues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column(
            "competition_type",
            sa.Enum(
                "league",
                "cup",
                "international",
                "organisation",
                name="competition_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "competition_type IN ('league', 'cup', 'international', 'organisation')",
            name=op.f("ck_leagues_competition_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_leagues_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leagues")),
        sa.UniqueConstraint("slug", name=op.f("uq_leagues_slug")),
    )
    with op.batch_alter_table("leagues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leagues_sport_id"), ["sport_id"], unique=False)

    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column(
            "hyperparameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("training_window_start", sa.Date(), nullable=True),
        sa.Column("training_window_end", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_model_versions_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_model_versions_name")),
    )
    with op.batch_alter_table("model_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_versions_sport_id"), ["sport_id"], unique=False)

    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("normalized_name", sa.String(length=150), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("position", sa.String(length=50), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_players_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_players_sport_id"), ["sport_id"], unique=False)
        batch_op.create_index(
            "ix_players_sport_id_normalized_name", ["sport_id", "normalized_name"], unique=False
        )

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("normalized_name", sa.String(length=150), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("logo_url", sa.String(length=300), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], name=op.f("fk_teams_sport_id_sports")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_sport_id"), ["sport_id"], unique=False)
        batch_op.create_index(
            "ix_teams_sport_id_normalized_name", ["sport_id", "normalized_name"], unique=False
        )

    op.create_table(
        "fighter_profiles",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("reach_cm", sa.Integer(), nullable=True),
        sa.Column("stance", sa.String(length=30), nullable=True),
        sa.Column("weight_class", sa.String(length=50), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("losses", sa.Integer(), nullable=True),
        sa.Column("draws", sa.Integer(), nullable=True),
        sa.Column("no_contests", sa.Integer(), nullable=True),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_fighter_profiles_player_id_players")
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("pk_fighter_profiles")),
    )
    op.create_table(
        "resolution_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "team",
                "player",
                "league",
                "fixture",
                name="entity_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.Column("league_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("raw_name", sa.String(length=200), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "candidates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "resolved",
                "ignored",
                name="resolution_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("resolved_entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolved_at", app.db.types.TZDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "entity_type IN ('team', 'player', 'league', 'fixture')",
            name=op.f("ck_resolution_queue_entity_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'resolved', 'ignored')",
            name=op.f("ck_resolution_queue_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["league_id"], ["leagues.id"], name=op.f("fk_resolution_queue_league_id_leagues")
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_resolution_queue_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_queue")),
    )
    with op.batch_alter_table("resolution_queue", schema=None) as batch_op:
        batch_op.create_index(
            "ix_resolution_queue_status_created", ["status", "created_at"], unique=False
        )

    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["league_id"], ["leagues.id"], name=op.f("fk_seasons_league_id_leagues")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("league_id", "name", name=op.f("uq_seasons_league_id")),
    )
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seasons_league_id"), ["league_id"], unique=False)

    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("start_time", app.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "in_play",
                "finished",
                "postponed",
                "cancelled",
                "unknown",
                name="fixture_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("round", sa.String(length=80), nullable=True),
        sa.Column("event_name", sa.String(length=150), nullable=True),
        sa.Column("venue_id", sa.Integer(), nullable=True),
        sa.Column("neutral_site", sa.Boolean(), nullable=False),
        sa.Column("scheduled_rounds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'in_play', 'finished', 'postponed', 'cancelled', 'unknown')",
            name=op.f("ck_fixtures_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["league_id"], ["leagues.id"], name=op.f("fk_fixtures_league_id_leagues")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_fixtures_season_id_seasons")
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_fixtures_sport_id_sports")
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"], ["venues.id"], name=op.f("fk_fixtures_venue_id_venues")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixtures")),
    )
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fixtures_league_id_start_time", ["league_id", "start_time"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fixtures_sport_id"), ["sport_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_fixtures_start_time"), ["start_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_fixtures_status"), ["status"], unique=False)

    op.create_table(
        "team_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("shirt_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_team_memberships_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_team_memberships_season_id_seasons")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_memberships_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_memberships")),
        sa.UniqueConstraint(
            "player_id", "team_id", "season_id", name=op.f("uq_team_memberships_player_id")
        ),
    )
    with op.batch_alter_table("team_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_team_memberships_player_id"), ["player_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_team_memberships_team_id"), ["team_id"], unique=False)

    op.create_table(
        "team_season_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("score_for", sa.Float(), nullable=True),
        sa.Column("score_against", sa.Float(), nullable=True),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_team_season_stats_season_id_seasons")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_season_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_season_stats")),
        sa.UniqueConstraint(
            "team_id", "season_id", "as_of", name=op.f("uq_team_season_stats_team_id")
        ),
    )
    with op.batch_alter_table("team_season_stats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_team_season_stats_season_id"), ["season_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_team_season_stats_team_id"), ["team_id"], unique=False)

    op.create_table(
        "fixture_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column(
            "side",
            sa.Enum("home", "away", name="side", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "side IN ('home', 'away')", name=op.f("ck_fixture_participants_side_valid")
        ),
        sa.CheckConstraint(
            "(team_id IS NULL) != (player_id IS NULL)",
            name=op.f("ck_fixture_participants_exactly_one_participant_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_fixture_participants_fixture_id_fixtures"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_fixture_participants_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_fixture_participants_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixture_participants")),
        sa.UniqueConstraint("fixture_id", "side", name=op.f("uq_fixture_participants_fixture_id")),
    )
    with op.batch_alter_table("fixture_participants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fixture_participants_fixture_id"), ["fixture_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fixture_participants_player_id"), ["player_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fixture_participants_team_id"), ["team_id"], unique=False
        )

    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker", sa.String(length=80), nullable=False),
        sa.Column("market", sa.String(length=80), nullable=False),
        sa.Column("selection", sa.String(length=120), nullable=False),
        sa.Column("line", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("price_decimal", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("captured_at", app.db.types.TZDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fixture_id"], ["fixtures.id"], name=op.f("fk_odds_snapshots_fixture_id_fixtures")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_odds_snapshots_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_snapshots")),
    )
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_odds_snapshots_captured_at"), ["captured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_odds_snapshots_fixture_id"), ["fixture_id"], unique=False
        )
        batch_op.create_index(
            "ix_odds_snapshots_fixture_market_time",
            ["fixture_id", "market", "captured_at"],
            unique=False,
        )

    op.create_table(
        "player_game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("minutes", sa.Float(), nullable=True),
        sa.Column(
            "stats",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"], ["fixtures.id"], name=op.f("fk_player_game_stats_fixture_id_fixtures")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_player_game_stats_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_player_game_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_game_stats")),
        sa.UniqueConstraint("player_id", "fixture_id", name=op.f("uq_player_game_stats_player_id")),
    )
    with op.batch_alter_table("player_game_stats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_game_stats_fixture_id"), ["fixture_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_player_game_stats_player_id"), ["player_id"], unique=False
        )

    op.create_table(
        "results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column(
            "winner_side",
            sa.Enum("home", "away", name="side", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "score_detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("finalized_at", app.db.types.TZDateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "winner_side IN ('home', 'away')", name=op.f("ck_results_winner_side_valid")
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"], ["fixtures.id"], name=op.f("fk_results_fixture_id_fixtures")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_results")),
        sa.UniqueConstraint("fixture_id", name=op.f("uq_results_fixture_id")),
    )
    op.create_table(
        "simulations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("n_iterations", sa.Integer(), nullable=False),
        sa.Column("artifact_path", sa.String(length=300), nullable=True),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"], ["fixtures.id"], name=op.f("fk_simulations_fixture_id_fixtures")
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_simulations_model_version_id_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulations")),
    )
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_simulations_fixture_id"), ["fixture_id"], unique=False)

    op.create_table(
        "bout_results",
        sa.Column("result_id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "ko_tko",
                "submission",
                "decision_unanimous",
                "decision_split",
                "decision_majority",
                "technical_decision",
                "draw",
                "no_contest",
                "disqualification",
                name="victory_method",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("end_round", sa.Integer(), nullable=True),
        sa.Column("end_time_seconds", sa.Integer(), nullable=True),
        sa.Column("detail", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "method IN ('ko_tko', 'submission', 'decision_unanimous', 'decision_split', 'decision_majority', 'technical_decision', 'draw', 'no_contest', 'disqualification')",
            name=op.f("ck_bout_results_method_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["result_id"], ["results.id"], name=op.f("fk_bout_results_result_id_results")
        ),
        sa.PrimaryKeyConstraint("result_id", name=op.f("pk_bout_results")),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.Column("market", sa.String(length=80), nullable=False),
        sa.Column("selection", sa.String(length=120), nullable=False),
        sa.Column("line", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("fair_price_decimal", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("low", "medium", "high", name="confidence", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("feature_hash", sa.String(length=64), nullable=False),
        sa.Column("generated_at", app.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column(
            "extra",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('low', 'medium', 'high')", name=op.f("ck_predictions_confidence_valid")
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"], ["fixtures.id"], name=op.f("fk_predictions_fixture_id_fixtures")
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
            name=op.f("fk_predictions_model_version_id_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_predictions_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_predictions_simulation_id_simulations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_predictions_fixture_id"), ["fixture_id"], unique=False)
        batch_op.create_index(
            "ix_predictions_fixture_market", ["fixture_id", "market"], unique=False
        )
        batch_op.create_index("ix_predictions_generated_at", ["generated_at"], unique=False)

    op.create_table(
        "bet_legs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bet_id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=True),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("market", sa.String(length=80), nullable=False),
        sa.Column("selection", sa.String(length=120), nullable=False),
        sa.Column("line", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("price_decimal", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("bookmaker", sa.String(length=80), nullable=True),
        sa.Column("model_probability", sa.Float(), nullable=True),
        sa.Column("implied_probability", sa.Float(), nullable=True),
        sa.Column("edge", sa.Float(), nullable=True),
        sa.Column(
            "result",
            sa.Enum(
                "win",
                "lose",
                "push",
                "void",
                "half_win",
                "half_lose",
                name="outcome",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.types.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "result IN ('win', 'lose', 'push', 'void', 'half_win', 'half_lose')",
            name=op.f("ck_bet_legs_result_valid"),
        ),
        sa.ForeignKeyConstraint(["bet_id"], ["bets.id"], name=op.f("fk_bet_legs_bet_id_bets")),
        sa.ForeignKeyConstraint(
            ["fixture_id"], ["fixtures.id"], name=op.f("fk_bet_legs_fixture_id_fixtures")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_bet_legs_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_bet_legs_prediction_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bet_legs")),
    )
    with op.batch_alter_table("bet_legs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bet_legs_bet_id"), ["bet_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bet_legs_fixture_id"), ["fixture_id"], unique=False)

    op.create_table(
        "settlements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=True),
        sa.Column("bet_leg_id", sa.Integer(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "win",
                "lose",
                "push",
                "void",
                "half_win",
                "half_lose",
                name="outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("auto", "manual", name="settlement_method", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("graded_at", app.db.types.TZDateTime(timezone=True), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('auto', 'manual')", name=op.f("ck_settlements_method_valid")
        ),
        sa.CheckConstraint(
            "outcome IN ('win', 'lose', 'push', 'void', 'half_win', 'half_lose')",
            name=op.f("ck_settlements_outcome_valid"),
        ),
        sa.CheckConstraint(
            "(prediction_id IS NULL) != (bet_leg_id IS NULL)",
            name=op.f("ck_settlements_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["bet_leg_id"], ["bet_legs.id"], name=op.f("fk_settlements_bet_leg_id_bet_legs")
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
            name=op.f("fk_settlements_prediction_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlements")),
    )
    with op.batch_alter_table("settlements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settlements_bet_leg_id"), ["bet_leg_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_settlements_prediction_id"), ["prediction_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settlements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settlements_prediction_id"))
        batch_op.drop_index(batch_op.f("ix_settlements_bet_leg_id"))

    op.drop_table("settlements")
    with op.batch_alter_table("bet_legs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bet_legs_fixture_id"))
        batch_op.drop_index(batch_op.f("ix_bet_legs_bet_id"))

    op.drop_table("bet_legs")
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index("ix_predictions_generated_at")
        batch_op.drop_index("ix_predictions_fixture_market")
        batch_op.drop_index(batch_op.f("ix_predictions_fixture_id"))

    op.drop_table("predictions")
    op.drop_table("bout_results")
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulations_fixture_id"))

    op.drop_table("simulations")
    op.drop_table("results")
    with op.batch_alter_table("player_game_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_game_stats_player_id"))
        batch_op.drop_index(batch_op.f("ix_player_game_stats_fixture_id"))

    op.drop_table("player_game_stats")
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_odds_snapshots_fixture_market_time")
        batch_op.drop_index(batch_op.f("ix_odds_snapshots_fixture_id"))
        batch_op.drop_index(batch_op.f("ix_odds_snapshots_captured_at"))

    op.drop_table("odds_snapshots")
    with op.batch_alter_table("fixture_participants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fixture_participants_team_id"))
        batch_op.drop_index(batch_op.f("ix_fixture_participants_player_id"))
        batch_op.drop_index(batch_op.f("ix_fixture_participants_fixture_id"))

    op.drop_table("fixture_participants")
    with op.batch_alter_table("team_season_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_season_stats_team_id"))
        batch_op.drop_index(batch_op.f("ix_team_season_stats_season_id"))

    op.drop_table("team_season_stats")
    with op.batch_alter_table("team_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_memberships_team_id"))
        batch_op.drop_index(batch_op.f("ix_team_memberships_player_id"))

    op.drop_table("team_memberships")
    with op.batch_alter_table("fixtures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fixtures_status"))
        batch_op.drop_index(batch_op.f("ix_fixtures_start_time"))
        batch_op.drop_index(batch_op.f("ix_fixtures_sport_id"))
        batch_op.drop_index("ix_fixtures_league_id_start_time")

    op.drop_table("fixtures")
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_seasons_league_id"))

    op.drop_table("seasons")
    with op.batch_alter_table("resolution_queue", schema=None) as batch_op:
        batch_op.drop_index("ix_resolution_queue_status_created")

    op.drop_table("resolution_queue")
    op.drop_table("fighter_profiles")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index("ix_teams_sport_id_normalized_name")
        batch_op.drop_index(batch_op.f("ix_teams_sport_id"))

    op.drop_table("teams")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("ix_players_sport_id_normalized_name")
        batch_op.drop_index(batch_op.f("ix_players_sport_id"))

    op.drop_table("players")
    with op.batch_alter_table("model_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_versions_sport_id"))

    op.drop_table("model_versions")
    with op.batch_alter_table("leagues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leagues_sport_id"))

    op.drop_table("leagues")
    with op.batch_alter_table("entity_aliases", schema=None) as batch_op:
        batch_op.drop_index("ix_entity_aliases_lookup")
        batch_op.drop_index(batch_op.f("ix_entity_aliases_entity_id"))

    op.drop_table("entity_aliases")
    with op.batch_alter_table("venues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venues_name"))

    op.drop_table("venues")
    op.drop_table("sports")
    with op.batch_alter_table("raw_ingest", schema=None) as batch_op:
        batch_op.drop_index("ix_raw_ingest_provider_endpoint_time")
        batch_op.drop_index(batch_op.f("ix_raw_ingest_fetched_at"))
        batch_op.drop_index(batch_op.f("ix_raw_ingest_content_hash"))

    op.drop_table("raw_ingest")
    with op.batch_alter_table("ingest_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingest_jobs_status"))
        batch_op.drop_index("ix_ingest_jobs_name_started")

    op.drop_table("ingest_jobs")
    with op.batch_alter_table("bets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bets_status"))

    op.drop_table("bets")
    # ### end Alembic commands ###
